# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: bolu.dev | 💻 + 🧬 + 📸 = 🤯
email: bluevires (at) gmail (dot) com
description: "Thoughts and notes on programming, data science and other things"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bolu.dev" # the base hostname & protocol for your site

# Social
twitter_username: blu3ness
github_username:  bolu-atx
linkedin_username: iambolu

# posts per page
paginate: 15

# Build settings
markdown: kramdown
syntax_highlighter: rouge
excerpt_separator: <!--more-->
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'highlight'
plugins:
  - jekyll-paginate

sass:
  style: expanded
  sourcemap: development